version: "3"
services:
  client:
    container_name: monke_code_speedtyper_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
